set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(MINGW_TRIPLE "$ENV{MINGW_TRIPLE}" CACHE STRING "MinGW-w64 toolchain prefix")
if(NOT MINGW_TRIPLE)
  set(MINGW_TRIPLE x86_64-w64-mingw32 CACHE STRING "MinGW-w64 toolchain prefix" FORCE)
endif()

set(CMAKE_C_COMPILER ${MINGW_TRIPLE}-gcc)
set(CMAKE_CXX_COMPILER ${MINGW_TRIPLE}-g++)
set(CMAKE_RC_COMPILER ${MINGW_TRIPLE}-windres)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
